### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by SergiuCip** [thias/puppet-nagios#48]
I have just tried to install your module, but unfortunately was complaining that it could not find the ::apache_httpd and php::mod class which were resolved after I have installed extra 2 modules: thias-php and apache_httpd is that right?

**Comment by thias** [comment]
Correct. Those aren't hard dependencies because all of that semi-automatic web server part may be disabled in order to use other modules if required. I know it's not ideal, but I'm sure I'd have many more complaints from people who prefer using their own (or the puppetlabs) httpd and php modules if this module automatically pulled in mine.
