### ISSUE TITLE
nagios-plugins-linux_raid

### ISSUE THREAD

**Issue by a-dekker** [thias/puppet-nagios#49]
Thias,

In EPEL7, nagios-plugins-linux_raid is no longer included in nagios-plugins-2.0.1-1.el7.

I guess it is related to this changelog on nagios-plugins-2.0.1-1.el7.x86_64.rpm
- Wed Oct 23 2013 Jose Pedro Oliveira <jpo at di.uminho.pt> - 1.5-1
  - No linux_raid subpackage (the contrib directory was removed)

There seems to be no way to control the individual installed nagios-plugins components. So could you remove this plugin dependency, or make it configurable in some way?

**Comment by thias** [comment]
Could you give a bit more detail about how you've seen this problem? For RHEL/Fedora, all of the individual plugins sub-packages are virtual resources, and realized only when needed, and as far as I can tell, none of the included checks in my module make use of the linux_raid plugin.

I just tried adding a `nagios-plugins-foo` to the `$nagios_plugins_packages` array in `params.pp` and none of my clients complain, as they only have installed the few plugins that their checks require (as expected).

**Comment by a-dekker** [comment]
It always tries to install this linux raid plugin rpm (although we do not use it).
The result is the following error message during a puppet run:
```bash
Error: Execution of '/bin/yum -d 0 -e 0 -y install nagios-plugins-linux_raid' returned 1: Error: Nothing to do
Error: /Stage[main]/Nagios::Params/Package[nagios-plugins-linux_raid]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y install nagios-plugins-linux_raid' returned 1: Error: Nothing to do
```

**Comment by rwf14f** [comment]
I ran into the same problem. In my case the culprit was the following statement:
    `Yumrepo <| |> -> Package <| |>`
which I used to get all the yumrepos set up before the package installations. Unfortunately this also realises all virtual package resources (which is mentioned in the puppet docs, but wasn't a problem so far, because I hadn't encountered a module that uses virtual packages until now).

You should check all your other modules for a package resource collector that's generic enough to realise the nagios-plugins-linux_raid package (e.g. `Package <| |>`) and fix it there.

Hope this information helps,
Robert

**Comment by a-dekker** [comment]
Thanks for your reply rwf14f.
We do use a similar statement in serveral parts of our code. I will have a closer look at it, and report back within a few weeks (as it is holiday season).

**Comment by a-dekker** [comment]
I am pretty sure the Yumrepo statement is the culprit. But working around this will take us too much time atm, so we will stick to our workaround (meaning a dummy package to resolve the dependency).
